// =====================================================================
// TRAMI ESPAÑA - Datos editoriales de trámites (Versión 8)
// Contenido real y útil: >=6 trámites por categoría.
// =====================================================================
module.exports = [
// ============ IDENTIDAD (4 nuevos -> 6 en total) ============
{ cat:'identidad', t:'Primera expedición del Documento Nacional de Identidad (DNI)', s:'primera-expedicion-dni',
  sd:'Tramita por primera vez tu DNI: cita previa, documentación necesaria y tasas.',
  d:'El DNI es el documento oficial que acredita la identidad y la nacionalidad española. La primera expedición debe realizarse en persona en una oficina de expedición, previa cita, y se entrega en el mismo acto. Obligatorio a partir de los 14 años.',
  cost:'12,30 € (tasa)', dur:'1 hora (con cita previa)', url:'https://www.dnielectronico.es',
  req:['Tener nacionalidad española.','Acudir en persona a la oficina de expedición con cita previa.','Ser mayor de 14 años (los menores deben ir acompañados de su representante legal).','Abonar la tasa de expedición.'],
  docs:[['Certificado literal de nacimiento del Registro Civil',true],['Certificado de empadronamiento vigente',true],['Fotografía reciente a color (32x26 mm)',true],['DNI del representante legal (si eres menor)',true]],
  steps:[['Solicita cita previa','Reserva tu cita en la web oficial del DNI electrónico o por teléfono.'],['Reúne la documentación','Prepara el certificado de nacimiento, empadronamiento y la fotografía.'],['Acude a la oficina','Ve a la oficina asignada en la fecha y hora indicadas y abona la tasa.'],['Recibe tu DNI','El documento se entrega en el mismo acto tras registrar tus datos biométricos.']],
  links:[['Cita previa DNI','https://www.citapreviadnie.es','appointment'],['Información oficial del DNI electrónico','https://www.dnielectronico.es','official']] },
{ cat:'identidad', t:'Expedición y renovación del pasaporte ordinario', s:'expedicion-pasaporte',
  sd:'Obtén o renueva tu pasaporte ordinario: requisitos, cita previa y tasa vigente.',
  d:'El pasaporte ordinario es el documento que acredita la identidad y nacionalidad española fuera del país. Se expide en oficinas de expedición (comisarías) con cita previa y tiene una vigencia de 10 años para adultos.',
  cost:'30 € (tasa)', dur:'45 minutos (con cita previa)', url:'https://www.policia.es',
  req:['Acudir personalmente a la oficina de expedición.','Presentar DNI o NIE vigente en vigor.','Abonar la tasa de expedición.','En renovación, entregar el pasaporte anterior (salvo pérdida o robo).'],
  docs:[['DNI vigente del solicitante',true],['Fotografía reciente a color (32x26 mm)',true],['Justificante de pago de la tasa',true],['Denuncia policial (solo en caso de pérdida o robo)',false]],
  steps:[['Pide cita previa','Reserva cita en la web o el teléfono oficial de la Policía Nacional.'],['Prepara la documentación','DNI, fotografía reciente y justificante del pago de la tasa.'],['Acude a la cita','El personal tomará tus datos y firma en la oficina.'],['Recogida en el mismo acto','El pasaporte se entrega normalmente el mismo día tras la expedición.']],
  links:[['Cita previa pasaporte (Policía Nacional)','https://www.citapreviapolicia.es','appointment'],['Policía Nacional - Pasaportes','https://www.policia.es','official']] },
{ cat:'identidad', t:'Registro y activación de Cl@ve (sistema de identificación)', s:'registro-clave',
  sd:'Date de alta en Cl@ve, el sistema público de identificación para trámites online.',
  d:'Cl@ve es la plataforma común de identificación, autenticación y firma electrónica de las administraciones públicas españolas. Permite realizar trámites online con una única cuenta mediante Cl@ve PIN o Cl@ve Permanente.',
  cost:'Gratuito', dur:'10 minutos', url:'https://clave.gob.es',
  req:['Ser mayor de edad o menor con autorización.','Disponer de DNI/NIE o poder identificarse con certificado digital.','Facilitar un número de móvil y un email válidos.'],
  docs:[['DNI o NIE',true],['Número de teléfono móvil',true],['Dirección de correo electrónico',true]],
  steps:[['Accede al portal de Cl@ve','Entra en clave.gob.es y elige la opción de registro.'],['Identifícate','Usa DNI electrónico, certificado digital o comparecencia presencial.'],['Configura tu cuenta','Añade móvil y email y elige el sistema de acceso (PIN o permanente).'],['Confirma el alta','Introduce el código recibido por SMS para activar tu cuenta.']],
  links:[['Portal oficial de Cl@ve','https://clave.gob.es','official']] },
{ cat:'identidad', t:'Certificado digital de persona física (FNMT)', s:'certificado-digital-fnmt',
  sd:'Solicita tu certificado digital FNMT para firmar y realizar trámites online.',
  d:'El certificado digital de la Fábrica Nacional de Moneda y Timbre (FNMT) identifica a la persona física en sus relaciones con las administraciones públicas y entidades privadas, permitiendo firmar electrónicamente cualquier trámite.',
  cost:'Gratuito', dur:'2 días hábiles (solicitud y acreditación)', url:'https://www.sede.fnmt.gob.es',
  req:['Tener DNI o NIE válido.','Realizar la solicitud online desde el navegador.','Acreditar tu identidad presencialmente en una oficina de registro.','Descargar el certificado desde el mismo equipo donde lo solicitaste.'],
  docs:[['DNI o NIE del solicitante',true],['Código de solicitud generado online',true]],
  steps:[['Solicita el certificado online','Cumplimenta el formulario en la sede de la FNMT con tus datos.'],['Acredita tu identidad','Acude a una oficina de acreditación con tu DNI y el código de solicitud.'],['Descarga el certificado','Tras la acreditación, descarga e instala el certificado en tu navegador.'],['Realiza una copia de seguridad','Guarda una copia de tu certificado y contraseña en lugar seguro.']],
  links:[['Sede electrónica FNMT-RCM','https://www.sede.fnmt.gob.es','official']] },

// ============ EMPADRONAMIENTO (4) ============
{ cat:'empadronamiento', t:'Renovación del empadronamiento municipal', s:'renovacion-empadronamiento',
  sd:'Renueva periódicamente tu inscripción en el padrón municipal de habitantes.',
  d:'Los extranjeros no comunitarios sin autorización de residencia permanente deben renovar su inscripción padronal cada 2 años. Si no se renueva en plazo, el Ayuntamiento puede dar de baja la inscripción y se pierden derechos vinculados.',
  cost:'Gratuito', dur:'20 minutos', url:'https://administracion.gob.es/pag_Home/ciudadanos/queNecesitoHago/Documento-empadronamiento.html',
  req:['Estar inscrito en el padrón del municipio.','Renovar antes del vencimiento del periodo de 2 años.','Acudir en persona o renovar online si el ayuntamiento lo permite.'],
  docs:[['DNI, NIE o pasaporte vigente',true],['Certificado o volante de empadronamiento anterior',false],['Justificante de residencia (alquiler o factura)',false]],
  steps:[['Comprueba el vencimiento','El ayuntamiento notifica el periodo de renovación por correo.'],['Pide cita','Presencial u online según el municipio.'],['Presenta la documentación','Identidad y justificantes de residencia actualizados.'],['Obtén el justificante','La renovación mantiene tus derechos y servicios municipales.']],
  links:[['Administración española - Empadronamiento','https://administracion.gob.es','information']] },
{ cat:'empadronamiento', t:'Cambio de domicilio en el padrón municipal', s:'cambio-domicilio-empadronamiento',
  sd:'Actualiza tu empadronamiento al cambiar de vivienda dentro o fuera del municipio.',
  d:'Todo ciudadano debe empadronarse en el municipio donde resida habitualmente. Al mudarte, comunica el cambio de domicilio para que conste tu dirección actual y puedas ejercer derechos como sanidad, escolarización o votar en tu nueva circunscripción.',
  cost:'Gratuito', dur:'20 minutos', url:'https://administracion.gob.es/pag_Home/ciudadanos/queNecesitoHago/Documento-empadronamiento.html',
  req:['Residir realmente en el nuevo domicilio.','Solicitar el cambio en el ayuntamiento de la nueva residencia.','Acreditar la ocupación de la vivienda con un documento válido.'],
  docs:[['DNI, NIE o pasaporte de los empadronados',true],['Contrato de alquiler, escritura o autorización del propietario',true],['Última factura de suministros',false]],
  steps:[['Pide cita en el nuevo ayuntamiento','También en oficinas de atención al ciudadano.'],['Aporta el justificante','Contrato, escritura o autorización del titular de la vivienda.'],['Firma la solicitud','Se actualiza la inscripción de toda la unidad familiar.'],['Pide el certificado nuevo','Con la nueva dirección, si lo necesitas para otros trámites.']],
  links:[['Administración española - Empadronamiento','https://administracion.gob.es','information']] },
{ cat:'empadronamiento', t:'Certificado de empadronamiento', s:'certificado-empadronamiento',
  sd:'Solicita el certificado oficial que acredita tu empadronamiento y antigüedad.',
  d:'El certificado de empadronamiento acredita oficialmente tu inscripción en el padrón, la dirección habitual y la antigüedad de residencia. Es imprescindible para trámites de extranjería, matrimonio, escolarización o compra de vehículos.',
  cost:'Gratuito', dur:'15 minutos (o por correo en 5 días)', url:'https://administracion.gob.es/pag_Home/ciudadanos/queNecesitoHago/Documento-empadronamiento.html',
  req:['Estar inscrito en el padrón municipal.','Ser la persona empadronada o tener su autorización.','Indicar la finalidad del certificado.'],
  docs:[['DNI, NIE o pasaporte del solicitante',true],['Autorización firmada (si se pide para otra persona)',false]],
  steps:[['Solicita el certificado','Presencialmente, por teléfono o en la sede online del ayuntamiento.'],['Acredita tu identidad','Con DNI/NIE o firma digital mediante Cl@ve.'],['Recibe el documento','Entrega inmediata o envío por correo postal.']],
  links:[['Administración española - Empadronamiento','https://administracion.gob.es','information']] },
{ cat:'empadronamiento', t:'Volante de empadronamiento', s:'volante-empadronamiento',
  sd:'Obtén el volante informativo de empadronamiento, rápido y sin coste.',
  d:'El volante de empadronamiento es un documento informativo que refleja los datos de la inscripción padronal. A diferencia del certificado, no tiene carácter formal documental, pero sirve para trámites administrativos generales y se expide al instante.',
  cost:'Gratuito', dur:'10 minutos', url:'https://administracion.gob.es/pag_Home/ciudadanos/queNecesitoHago/Documento-empadronamiento.html',
  req:['Estar inscrito en el padrón municipal.','Identificarse con DNI, NIE o pasaporte.','Solicitar únicamente los datos informativos necesarios.'],
  docs:[['DNI, NIE o pasaporte',true],['Justificante de la dirección (si el volante la incluye)',false]],
  steps:[['Acude a la oficina municipal','O accede a la sede electrónica de tu ayuntamiento.'],['Solicita el volante','Indica los datos que deben figurar (dirección, convivientes).'],['Recoge el documento','Se entrega al momento, impreso o digital.']],
  links:[['Administración española - Empadronamiento','https://administracion.gob.es','information']] },

// ============ EMPADRONAMIENTO (1) + LABORAL (3) ============
{ cat:'empadronamiento', t:'Empadronamiento de menores de edad', s:'empadronamiento-menores',
  sd:'Inscribe a un menor en el padrón municipal: documentación y pasos a seguir.',
  d:'Los menores deben estar empadronados en el domicilio de sus padres o tutores. Es necesario para la escolarización, la tarjeta sanitaria y las prestaciones familiares, y puede realizarse en el mismo acto que el alta de los padres.',
  cost:'Gratuito', dur:'20 minutos', url:'https://administracion.gob.es/pag_Home/ciudadanos/queNecesitoHago/Documento-empadronamiento.html',
  req:['Que los padres o tutores estén empadronados (o empadronarse a la vez).','Presentar la partida de nacimiento o documento del menor.','Acreditar la tutela o representación legal si procede.'],
  docs:[['Libro de familia o certificado de nacimiento',true],['DNI, NIE o pasaporte del menor (si lo tiene)',true],['DNI o NIE de los padres o tutores',true]],
  steps:[['Solicita cita en el ayuntamiento','En muchas oficinas se atiende sin cita.'],['Presenta la documentación','Partida de nacimiento y documentos de identidad.'],['Firma el alta padronal','Firman ambos progenitores o el tutor legal.'],['Solicita el certificado','Para escuela, sanidad o prestaciones.']],
  links:[['Administración española - Empadronamiento','https://administracion.gob.es','information']] },
{ cat:'laboral', t:'Solicitud del informe de Vida Laboral', s:'vida-laboral',
  sd:'Descarga tu informe de vida laboral: historial completo de cotizaciones a la SS.',
  d:'La vida laboral es un documento oficial de la Seguridad Social que recoge todas las empresas en las que has trabajado y las fechas de alta y baja. Es imprescindible para calcular jubilaciones, solicitar ayudas o acreditar experiencia.',
  cost:'Gratuito', dur:'5 minutos', url:'https://sede.administracionespublicas.gob.es/pagFront/indexInformacionVidaLaboral',
  req:['Tener alguna cotización previa a la Seguridad Social.','Identificarse con Cl@ve, certificado digital o DNI electrónico.','Elegir informe detallado o no detallado.'],
  docs:[['Sistema de identificación (Cl@ve o certificado digital)',true],['NUSS o DNI',false]],
  steps:[['Accede al servicio online','En la sede de la Seguridad Social - Vida Laboral.'],['Identifícate','Con Cl@ve, certificado digital o DNI electrónico.'],['Solicita el informe','Elige tipo de informe y fecha de inicio.'],['Descarga el PDF','Se genera al momento y puedes guardarlo o imprimirlo.']],
  links:[['Solicitud de vida laboral','https://sede.administracionespublicas.gob.es/pagFront/indexInformacionVidaLaboral','official']] },
{ cat:'laboral', t:'Inscripción como demandante de empleo', s:'inscripcion-demandante-empleo',
  sd:'Date de alta como demandante de empleo y accede a ofertas y prestaciones.',
  d:'La inscripción como demandante de empleo («carné de paro») permite acceder a ofertas de los servicios públicos de empleo y es requisito previo para cobrar el desempleo. Debe renovarse periódicamente para mantener el alta.',
  cost:'Gratuito', dur:'30 minutos', url:'https://sede.sepe.gob.es',
  req:['Tener 16 o más años y estar en edad laboral.','Inscribirse en el servicio público de empleo de tu comunidad.','Renovar la demanda en las fechas asignadas.','Disponer de DNI/NIE en vigor.'],
  docs:[['DNI o NIE en vigor',true],['Documento de afiliación a la Seguridad Social',false],['Justificantes de formación (opcional)',false]],
  steps:[['Prepara la documentación','Identidad, contacto y cualificación profesional.'],['Inscríbete','Presencialmente en oficina u online en tu servicio de empleo.'],['Recibe la demanda','Con la fecha de renovación que deberás respetar.'],['Renueva','Según el calendario indicado para mantener el alta.']],
  links:[['SEPE - Sede electrónica','https://sede.sepe.gob.es','official']] },
{ cat:'laboral', t:'Subsidio para mayores de 52 años', s:'subsidio-mayores-52-anos',
  sd:'Solicita el subsidio del SEPE para desempleados mayores de 52 años.',
  d:'El subsidio para mayores de 52 años es una prestación asistencial del SEPE para quienes han agotado su prestación contributiva. Mientras se percibe, la Seguridad Social cotiza para la jubilación al 125 % de la base mínima.',
  cost:'Gratuito', dur:'20 minutos', url:'https://sede.sepe.gob.es',
  req:['Ser mayor de 52 años y menor de la edad ordinaria de jubilación.','Haber agotado la prestación contributiva.','Acreditar rentas inferiores al 75 % del SMI.','Acreditar al menos 6 años cotizados en la vida laboral.'],
  docs:[['Modelo oficial de solicitud del SEPE',true],['DNI o NIE',true],['Justificantes de rentas de la unidad familiar',true],['Vida laboral (se consulta por el SEPE)',false]],
  steps:[['Reúne la documentación','Vida laboral y justificantes de rentas familiares.'],['Presenta la solicitud','En oficina de prestaciones o sede electrónica del SEPE.'],['Espera la resolución','Plazo máximo de 3 meses.'],['Cobra el subsidio','Renovando la demanda y manteniendo la búsqueda activa.']],
  links:[['SEPE - Prestaciones','https://sede.sepe.gob.es','official']] },

// ============ LABORAL (2) + SEGURIDAD SOCIAL (2) ============
{ cat:'laboral', t:'Subsidio por desempleo (agotamiento de la prestación)', s:'subsidio-desempleo-agotamiento',
  sd:'Pide el subsidio asistencial al agotar tu prestación contributiva de desempleo.',
  d:'El subsidio por desempleo es la prestación asistencial que se solicita al agotar el paro contributivo o en otras causas reconocidas (responsabilidades familiares, mayores de 45 años). Requiere carencia de rentas y estar inscrito como demandante.',
  cost:'Gratuito', dur:'20 minutos', url:'https://sede.sepe.gob.es',
  req:['Haber agotado la prestación contributiva o estar en causa legal.','Estar inscrito como demandante de empleo.','No superar el límite de rentas (75 % del SMI).','Solicitarlo en los 15 días siguientes al agotamiento.'],
  docs:[['Modelo oficial de solicitud del SEPE',true],['DNI o NIE',true],['Justificantes de rentas de la unidad familiar',true],['Justificante de inscripción como demandante',false]],
  steps:[['Comprueba los plazos','15 días desde el agotamiento de la prestación.'],['Recopila justificantes','Rentas familiares y fin del paro contributivo.'],['Presenta la solicitud','En oficina o sede electrónica del SEPE.'],['Firma el compromiso de actividad','Y mantén activa la búsqueda de empleo.']],
  links:[['SEPE - Prestaciones','https://sede.sepe.gob.es','official']] },
{ cat:'laboral', t:'Baja médica por incapacidad temporal (IT)', s:'baja-medica-incapacidad-temporal',
  sd:'Gestiona tu baja médica: expedición, seguimiento y alta de la incapacidad temporal.',
  d:'La incapacidad temporal es la situación del trabajador temporalmente imposibilitado para trabajar por enfermedad común, accidente o maternidad. Los partes de baja, confirmación y alta determinan el cobro del subsidio correspondiente durante la ausencia.',
  cost:'Gratuito', dur:'15 minutos', url:'https://sede.seg-social.gob.es',
  req:['Estar en situación de IT reconocida por el médico.','Entregar el parte de baja a la empresa en 5 días.','Pasar los reconocimientos médicos de seguimiento.'],
  docs:[['Parte médico de baja (copia para la empresa)',true],['DNI o NIE del trabajador',true],['Informes médicos de seguimiento',false]],
  steps:[['Acude a tu centro de salud','El médico evalúa y expide el parte de baja.'],['Entrega el parte','A tu empresa en un máximo de 5 días.'],['Pasa los reconocimientos','Revisiones de confirmación de la baja.'],['Recibe el alta médica','La expide el INSS o tu médico según el caso.']],
  links:[['Seguridad Social - Sede electrónica','https://sede.seg-social.gob.es','official']] },
{ cat:'seguridad-social', t:'Solicitud de la Tarjeta Sanitaria Europea (TSE)', s:'tarjeta-sanitaria-europea',
  sd:'Pide la Tarjeta Sanitaria Europea para recibir asistencia médica en la UE.',
  d:'La Tarjeta Sanitaria Europea garantiza la atención médica necesaria durante estancias temporales en la Unión Europea, Espacio Económico Europeo y Suiza, en las mismas condiciones que los asegurados del país visitado.',
  cost:'Gratuito', dur:'15 minutos (envío en 10 días)', url:'https://sede.inss.gob.es',
  req:['Estar cubierto por la sanidad pública española.','Solicitarla para cada miembro de la unidad familiar.','Caduca a la vez que la cobertura del titular.'],
  docs:[['Tarjeta sanitaria individual',true],['DNI o NIE del titular',true],['Datos del banco (para envío de tarjeta, según organismo)',false]],
  steps:[['Identifícate en la sede del INSS','Con Cl@ve, certificado digital o en oficina presencial.'],['Solicita la TSE','Indica los beneficiarios de la unidad familiar.'],['Recibe la tarjeta','Llega por correo postal en unos 10 días hábiles.'],['Comprueba la caducidad','Renuévala cuando venza la cobertura.']],
  links:[['INSS - Sede electrónica','https://sede.inss.gob.es','official']] },
{ cat:'seguridad-social', t:'Solicitud de la pensión de jubilación contributiva', s:'pension-jubilacion',
  sd:'Solicita tu pensión de jubilación ante el INSS: requisitos y plazos clave.',
  d:'La pensión de jubilación contributiva es la prestación económica vitalicia que reconoce la Seguridad Social a quienes alcanzan la edad legal de jubilación y acreditan el periodo mínimo de cotización. Se solicita hasta 3 meses antes de la fecha prevista.',
  cost:'Gratuito', dur:'20 minutos', url:'https://sede.seg-social.gob.es',
  req:['Tener al menos 15 años de cotización (2 dentro de los últimos 15).','Alcanzar la edad legal ordinaria o anticipada de jubilación.','Presentar la solicitud hasta 3 meses antes de la fecha prevista.'],
  docs:[['Modelo oficial de solicitud de jubilación',true],['DNI o NIE del solicitante',true],['Datos bancarios (IBAN)',true],['Libro de familia o documentos de familiares',false]],
  steps:[['Solicita tu vida laboral','Para verificar tus cotizaciones antes de presentar la solicitud.'],['Presenta la solicitud','En la sede del INSS, con Cl@ve o certificado digital.'],['Aporta la documentación','Identidad, IBAN y justificantes familiares.'],['Recibe la resolución','El INSS responde y fija la cuantía y fecha de efecto.']],
  links:[['INSS - Jubilación','https://sede.seg-social.gob.es','official']] },

// ============ SEGURIDAD SOCIAL (4) ============
{ cat:'seguridad-social', t:'Reconocimiento de la situación de dependencia (Ley de Dependencia)', s:'dependencia-valoracion',
  sd:'Solicita la valoración del grado de dependencia y accede a ayudas y servicios.',
  d:'La Ley de Dependencia reconoce derechos a las personas que necesitan ayuda para las actividades básicas de la vida diaria. Tras la solicitud, un equipo de valoración determina el grado y nivel, que abre el acceso a servicios y prestaciones económicas.',
  cost:'Gratuito', dur:'30 minutos (resolución en meses según CCAA)', url:'https://imserso.es',
  req:['Estar empadronado al menos un año en la comunidad autónoma (salvo menores).','Solicitar la valoración ante el organismo autonómico competente.','Permitir la visita del equipo de valoración al domicilio.'],
  docs:[['Solicitud oficial del organismo autonómico',true],['DNI o NIE de la persona dependiente y de quien la represente',true],['Informe médico o discapacidad reconocida (si se tiene)',false],['Documentación acreditativa de la representación legal',false]],
  steps:[['Presenta la solicitud','En los servicios sociales de tu comunidad autónoma.'],['Valoración del caso','Un equipo evalúa la situación en el domicilio o centro.'],['Resolución del grado','Se notifica el grado y nivel de dependencia.'],['Programa individual de atención','Se asignan servicios o prestaciones según el grado.']],
  links:[['IMSERSO - Dependencia','https://imserso.es','information']] },
{ cat:'seguridad-social', t:'Solicitud de la incapacidad permanente ante el INSS', s:'incapacidad-permanente',
  sd:'Solicita la incapacidad permanente: grados, documentación y evaluación médica.',
  d:'La incapacidad permanente es la prestación que reconoce la Seguridad Social cuando, tras tratarse una lesión o enfermedad, quedan secuelas reductoras de la capacidad laboral. Se determina tras la evaluación por el tribunal médico (EVI).',
  cost:'Gratuito', dur:'30 minutos', url:'https://sede.seg-social.gob.es',
  req:['Haber finalizado el periodo de incapacidad temporal o estar en situación asimilada.','Presentar la solicitud ante el INSS (directamente o tras el alta médica).','Acudir a la citación del tribunal médico (EVI).'],
  docs:[['Modelo oficial de solicitud del INSS',true],['DNI o NIE del solicitante',true],['Informes médicos actualizados de especialistas',true],['Vida laboral y empresa(s) donde se trabajó',false]],
  steps:[['Recopila informes médicos','Solicita informes detallados de tus especialistas.'],['Presenta la solicitud','En la sede del INSS o por vía administrativa.'],['Asiste a la evaluación','El EVI realizará el reconocimiento médico.'],['Resolución y revisión','El INSS notifica el grado y la cuantía de la pensión.']],
  links:[['INSS - Sede electrónica','https://sede.seg-social.gob.es','official']] },
{ cat:'seguridad-social', t:'Solicitud del Ingreso Mínimo Vital (IMV)', s:'ingreso-minimo-vital',
  sd:'Pide el Ingreso Mínimo Vital: renta mínima estatal para unidades familiares.',
  d:'El Ingreso Mínimo Vital es una prestación de la Seguridad Social que garantiza unos ingresos mínimos a las unidades de convivencia en situación de vulnerabilidad económica. La cuantía depende de los ingresos y del número de miembros del hogar.',
  cost:'Gratuito', dur:'30 minutos', url:'https://sede.seg-social.gob.es',
  req:['Tener residencia legal en España (mínimo 1 año si eres extranjero).','Estar al corriente de las obligaciones tributarias.','No superar los límites de rentas y patrimonio del hogar.','Presentar la solicitud junto con la documentación de la unidad de convivencia.'],
  docs:[['DNI o NIE de todos los miembros de la unidad',true],['Certificado de empadronamiento colectivo',true],['Justificantes de ingresos y patrimonio',true],['Número de cuenta bancaria (IBAN)',true]],
  steps:[['Usa el simulador oficial','Comprueba la posible elegibilidad en la web de la Seguridad Social.'],['Presenta la solicitud online','En la sede electrónica con Cl@ve o certificado digital.'],['Aporta la documentación','Identidad, empadronamiento e ingresos de la unidad.'],['Recibe la resolución','Si es favorable, el pago se abona mensualmente.']],
  links:[['Seguridad Social - IMV','https://sede.seg-social.gob.es','official']] },
{ cat:'seguridad-social', t:'Prestación por nacimiento o adopción de hijo', s:'prestacion-nacimiento-adopcion',
  sd:'Solicita la prestación económica por nacimiento, adopción o acogimiento.',
  d:'La prestación por nacimiento o adopción es un pago único a cargo de la Seguridad Social (el «cheque bebé»), abonado por cada hijo nacido o adoptado. También existen las prestaciones de maternidad y paternidad por suspensión de actividad.',
  cost:'Gratuito', dur:'15 minutos', url:'https://sede.seg-social.gob.es',
  req:['Estar afiliado y en alta (o situación asimilada) en la Seguridad Social.','Solicitarlo dentro del plazo establecido tras el nacimiento o adopción.','Tener la filiación inscrita en el Registro Civil.'],
  docs:[['Modelo oficial de solicitud',true],['DNI o NIE del progenitor solicitante',true],['Libro de familia o certificado literal de nacimiento',true],['Número de cuenta bancaria (IBAN)',true]],
  steps:[['Reúne la documentación','Certificado de nacimiento o libro de familia e IBAN.'],['Presenta la solicitud','En la sede electrónica de la Seguridad Social.'],['Espera el pago','Se abona como pago único en la cuenta indicada.'],['Comprueba las prestaciones por descanso','Las de maternidad/paternidad se tramitan aparte.']],
  links:[['Seguridad Social - Sede electrónica','https://sede.seg-social.gob.es','official']] },

// ============ FAMILIA (4) ============
{ cat:'familia', t:'Inscripción de nacimiento en el Registro Civil', s:'inscripcion-nacimiento-registro-civil',
  sd:'Inscribe a tu hijo en el Registro Civil: plazos y documentación necesaria.',
  d:'La inscripción de nacimiento es el acto que oficializa la existencia de una persona y determina su filiación. Debe realizarse en el Registro Civil del lugar de nacimiento en un plazo máximo de 8 días (o 30 si se justifica).',
  cost:'Gratuito', dur:'30 minutos', url:'https://sede.mjusticia.gob.es',
  req:['Nacimiento ocurrido en territorio español (o de padres españoles en el extranjero).','Presentar la declaración en el plazo legal (8 días, ampliable a 30).','Acudir con el documento de identidad de los progenitores.'],
  docs:[['Parte de alumbramiento o certificado médico de nacimiento',true],['DNI, NIE o pasaporte de los progenitores',true],['Libro de familia (si se dispone de él)',false]],
  steps:[['Acude al Registro Civil','El del lugar de nacimiento, con cita si es necesario.'],['Presenta el parte médico','El documento de alumbramiento del centro sanitario.'],['Declara los datos del recién nacido','Nombre, filiación y datos de los padres.'],['Recibe la inscripción','Se anota en el acta y puedes pedir certificado literal.']],
  links:[['Ministerio de Justicia - Registro Civil','https://sede.mjusticia.gob.es','official']] },
{ cat:'familia', t:'Solicitud del libro de familia (o libreta)', s:'libro-familia',
  sd:'Tramita el libro de familia o solicita la sustitución por certificados digitales.',
  d:'El libro de familia es el documento tradicional que acredita el estado civil y las relaciones familiares. Desde 2021, los recién nacidos ya no reciben libreta: se sustituye por certificados electrónicos, aunque sigue siendo posible obtenerla o renovarla.',
  cost:'Gratuito', dur:'20 minutos', url:'https://sede.mjusticia.gob.es',
  req:['Estar inscrito el matrimonio o nacimiento en el Registro Civil.','Solicitarlo en el Registro Civil competente.','Los trámites pueden requerir cita previa.'],
  docs:[['DNI o NIE de los solicitantes',true],['Certificado de matrimonio o de nacimiento',true]],
  steps:[['Pide cita en el Registro Civil','Presencial u online según la circunscripción.'],['Acredita la inscripción','Presenta certificados de matrimonio o nacimiento.'],['Recibe la libreta','Se emite en el mismo acto o en pocos días.'],['Alternativa digital','Solicita certificados electrónicos desde la sede de Justicia.']],
  links:[['Ministerio de Justicia - Sede','https://sede.mjusticia.gob.es','official']] },
{ cat:'familia', t:'Título de familia numerosa', s:'titulo-familia-numerosa',
  sd:'Solicita el título de familia numerosa y sus descuentos y beneficios.',
  d:'El título de familia numerosa acredita la condición de familia numerosa (general o especial) y da derecho a beneficios fiscales, educativos, de transporte y laboral. Lo expide la comunidad autónoma y tiene validez en todo el territorio nacional.',
  cost:'Gratuito', dur:'30 minutos (resolución en meses)', url:'https://administracion.gob.es',
  req:['Cumplir los requisitos legales de familia numerosa (número de hijos, discapacidad, etc.).','Estar empadronado en la comunidad autónoma que expide el título.','Solicitarlo ante el órgano autonómico competente.'],
  docs:[['Solicitud oficial de la comunidad autónoma',true],['Libro de familia o certificados de nacimiento de los hijos',true],['DNI o NIE de los padres y mayores de edad',true],['Certificados de discapacidad si procede',false]],
  steps:[['Comprueba los requisitos','Categoría general o especial según el número de hijos y circunstancias.'],['Presenta la solicitud','En el organismo autonómico correspondiente.'],['Adjunta la documentación familiar','Certificados de nacimiento, empadronamiento y discapacidad.'],['Recibe el título','Con foto y categoría; renuévalo según su vigencia.']],
  links:[['Administración española','https://administracion.gob.es','information']] },
{ cat:'familia', t:'Reconocimiento del grado de discapacidad (33 % o superior)', s:'grado-discapacidad',
  sd:'Solicita la valoración del grado de discapacidad y sus beneficios asociados.',
  d:'El reconocimiento del grado de discapacidad (mínimo 33 %) acredita oficialmente la situación y da acceso a prestaciones, exenciones fiscales, empleos reservados y ayudas. La valoración la realizan los equipos de valoración y orientación (EVO) autonómicos.',
  cost:'Gratuito', dur:'30 minutos', url:'https://imserso.es',
  req:['Tener una patología o condición valorable (física, psíquica, intelectual o sensorial).','Solicitar la valoración en la comunidad autónoma de residencia.','Acudir a la cita del equipo de valoración (EVO).'],
  docs:[['Solicitud oficial de la comunidad autónoma',true],['Informes médicos actualizados',true],['DNI o NIE del solicitante o representante',true],['Historial clínico relevante',false]],
  steps:[['Presenta la solicitud','En los servicios sociales o centro base de tu comunidad.'],['Aporta informes médicos','Cuanto más completos, mejor valoración.'],['Asiste a la valoración','El EVO evalúa las limitaciones funcionales.'],['Resolución del porcentaje','El grado abre el acceso a ayudas y beneficios.']],
  links:[['IMSERSO - Discapacidad','https://imserso.es','information']] },

// ============ FAMILIA (2) + VEHICULOS (2) ============
{ cat:'familia', t:'Prestación por hijo a cargo (Seguridad Social)', s:'prestacion-hijo-cargo',
  sd:'Solicita la asignación económica por hijo a cargo de la Seguridad Social.',
  d:'La asignación por hijo a cargo es una prestación mensual de la Seguridad Social para familias con hijos menores de 18 años o con discapacidad igual o superior al 18 %, siempre que los ingresos de la unidad familiar no superen el límite legal.',
  cost:'Gratuito', dur:'15 minutos', url:'https://sede.seg-social.gob.es',
  req:['Tener hijos menores de 18 años (o con discapacidad ≥ 18 %, sin límite de edad).','No superar el límite de ingresos anual de la familia.','Estar afiliado y en alta (o situación asimilada) en la Seguridad Social.'],
  docs:[['Modelo oficial de solicitud',true],['Libro de familia o certificados de nacimiento',true],['DNI o NIE del solicitante',true],['Número de cuenta bancaria (IBAN)',true]],
  steps:[['Comprueba los límites de renta','Dependen del número de hijos a cargo.'],['Presenta la solicitud','En la sede electrónica o dirección provincial del INSS.'],['Adjunta la documentación','Filiación, identidad e IBAN.'],['Cobra la asignación','Mensualmente mientras se mantengan los requisitos.']],
  links:[['Seguridad Social - Sede electrónica','https://sede.seg-social.gob.es','official']] },
{ cat:'familia', t:'Autorización de viaje para menores de edad', s:'autorizacion-viaje-menores',
  sd:'Tramita el consentimiento y la autorización de viaje de menores al extranjero.',
  d:'Los menores de edad que viajen fuera de España sin sus padres o con una sola persona adulta autorizada pueden necesitar una autorización de viaje o consentimiento expreso, tramitada ante notario, comisaría o de forma electrónica según el destino.',
  cost:'Aprox. 30-60 € (notarial) o gratuito (policial)', dur:'30 minutos', url:'https://www.policia.es',
  req:['Identificar a los progenitores o tutores legales.','Especificar destino, fechas y acompañante del menor.','Firmar el consentimiento ante la autoridad competente.'],
  docs:[['DNI o pasaporte del menor',true],['DNI o NIE de los padres o tutores',true],['Pasaporte y datos del acompañante adulto',true],['Libro de familia (para acreditar la filiación)',false]],
  steps:[['Elige la vía','Notarial (con coste) o policial ante la Comisaría Nacional.'],['Solicita cita','En notaría o en la oficina de expedición de la Policía Nacional.'],['Firma la autorización','Ambos progenitores o el que no viaja otorga el consentimiento.'],['Viaja con el documento','El menor debe llevar la autorización durante el viaje.']],
  links:[['Policía Nacional','https://www.policia.es','information']] },
{ cat:'vehiculos', t:'Renovación del permiso de conducción', s:'renovacion-permiso-conducir',
  sd:'Renueva tu permiso de conducir: psicotécnico, tasas y cita en la DGT o centros.',
  d:'El permiso de conducir debe renovarse periódicamente según la edad y las condiciones psicofísicas del titular. La renovación puede tramitarse en centros de reconocimiento de conductores o en las oficinas de la DGT, con el informe de aptitud psicofísica.',
  cost:'24,10 € (tasa 4.1) + informe médico', dur:'30 minutos', url:'https://sede.dgt.gob.es',
  req:['Superar el reconocimiento psicofísico (informe de aptitud).','No tener prohibida la conducción por resolución judicial.','Abonar la tasa 4.1 de la DGT.','Tramitarlo dentro de los últimos 3 meses de vigencia (o tras caducar).'],
  docs:[['DNI o NIE en vigor',true],['Informe de aptitud psicofísica del centro médico',true],['Fotografía reciente 32x26 mm',true],['Justificante de pago de la tasa',true]],
  steps:[['Pasa el psicotécnico','En un centro de reconocimiento de conductores autorizado.'],['Paga la tasa 4.1','Puede pagarse en el centro o en la web de la DGT.'],['Presenta la solicitud','En el propio centro o en una oficina de la DGT.'],['Recibe el nuevo permiso','Llega por correo en unas semanas; mientras tanto se entrega un justificante.']],
  links:[['DGT - Sede electrónica','https://sede.dgt.gob.es','official']] },
{ cat:'vehiculos', t:'Cambio de titularidad de un vehículo', s:'cambio-titularidad-vehiculo',
  sd:'Cambia la titularidad de un vehículo comprado o vendido ante la DGT.',
  d:'La transmisión de un vehículo exige inscribir el cambio de titularidad en la Jefatura Provincial de Tráfico (o en la sede electrónica de la DGT) en un plazo de 30 días desde la venta, para que el comprador figure como nuevo propietario.',
  cost:'54,60 € (tasa 4.1)', dur:'30 minutos', url:'https://sede.dgt.gob.es',
  req:['Realizar el trámite en los 30 días siguientes a la transmisión.','Estar el vehículo al corriente de ITV, seguros y sanciones.','Abonar la tasa 4.1 de la DGT.','Acreditar la transferencia con contrato u otro documento válido.'],
  docs:[['Contrato de compraventa o documento de transmisión',true],['DNI o NIE de comprador y vendedor',true],['Ficha técnica (permiso de circulación y tarjeta ITV)',true],['Justificante de pago de la tasa 4.1',true]],
  steps:[['Firma el contrato de compraventa','Ambas partes, con identificación y datos del vehículo.'],['Comprueba deudas y saneo','Sanciones, ITV y seguridad social del vendedor.'],['Tramita el cambio','En la sede electrónica DGT o en oficina con cita.'],['Recibe el nuevo permiso','Se envía por correo al nuevo titular.']],
  links:[['DGT - Trámites de vehículos','https://sede.dgt.gob.es','official']] },

// ============ VEHICULOS (4) ============
{ cat:'vehiculos', t:'Matriculación de un vehículo nuevo', s:'matriculacion-vehiculo',
  sd:'Matricula tu vehículo nuevo: tasas, documentación y primera ITV obligatoria.',
  d:'La matriculación es el trámite que asigna la matrícula y habilita la circulación del vehículo. Requiere el certificado de conformidad, el abono de la tasa DGT y, salvo exenciones, el IEDMT (impuesto de matriculación) cuando proceda.',
  cost:'99,80 € (tasa 4.1)', dur:'45 minutos', url:'https://sede.dgt.gob.es',
  req:['Tener el certificado de conformidad (COC) del fabricante.','Abonar la tasa 4.1 de la DGT.','Acreditar el seguro obligatorio en vigor.','Superar la primera ITV si el vehículo la requiere.'],
  docs:[['Certificado de conformidad europeo (COC)',true],['Factura de compra del vehículo',true],['DNI o NIE del titular',true],['Justificante de pago de tasas e impuestos',true]],
  steps:[['Reúne la documentación','COC, factura e identidad del titular.'],['Abona las tasas','Tasa DGT 4.1 e IEDMT si corresponde (modelo 620).'],['Solicita la matrícula','En la sede electrónica de la DGT o en oficina.'],['Recibe la documentación','Permiso de circulación y tarjeta ITV con la nueva matrícula.']],
  links:[['DGT - Sede electrónica','https://sede.dgt.gob.es','official']] },
{ cat:'vehiculos', t:'Baja temporal o definitiva de un vehículo', s:'baja-vehiculo',
  sd:'Da de baja tu vehículo: temporal por no circular o definitiva por desguace.',
  d:'La baja registral de un vehículo evita seguir pagando impuestos y seguros por un coche que ya no circula. La baja temporal impide circular por vía pública; la definitiva se tramita al entregar el vehículo a un centro de tratamiento de desguace autorizado (CAT).',
  cost:'Gratuito', dur:'30 minutos', url:'https://sede.dgt.gob.es',
  req:['Ser el titular registral del vehículo o acreditar la representación.','Para baja definitiva, entregar el vehículo a un CAT autorizado.','Quitar la baja temporal cuando se reanude la circulación.'],
  docs:[['DNI o NIE del titular',true],['Permiso de circulación y tarjeta ITV',true],['Certificado de destrucción del CAT (baja definitiva)',true]],
  steps:[['Elige el tipo de baja','Temporal (no circulará) o definitiva (desguace).'],['En baja definitiva, lleva el vehículo al CAT','El centro entrega el certificado de destrucción.'],['Tramita la baja','En la DGT con el certificado o la solicitud de baja temporal.'],['Guarda el justificante','Certifica que el vehículo no circula ni genera impuestos.']],
  links:[['DGT - Sede electrónica','https://sede.dgt.gob.es','official']] },
{ cat:'vehiculos', t:'Tarjeta de estacionamiento para personas con discapacidad', s:'tarjeta-aparcamiento-discapacidad',
  sd:'Solicita la tarjeta de aparcamiento reservado para personas con movilidad reducida.',
  d:'La tarjeta de estacionamiento para personas con discapacidad permite aparcar en plazas reservadas y en zonas con limitaciones de tiempo. La expiden los ayuntamientos previo reconocimiento de movilidad reducida y tiene validez en toda Europa.',
  cost:'Gratuito', dur:'30 minutos', url:'https://administracion.gob.es',
  req:['Tener reconocido el grado de discapacidad con movilidad reducida (o solicitud en trámite).','Solicitarla en el ayuntamiento donde resida la persona.','Renovarla según la vigencia indicada.'],
  docs:[['Solicitud municipal oficial',true],['Certificado de grado de discapacidad con movilidad reducida',true],['DNI o NIE de la persona solicitante',true],['Fotografía reciente',false]],
  steps:[['Acredita la movilidad reducida','Mediante el reconocimiento autonómico de discapacidad.'],['Solicita la tarjeta','En los servicios sociales u oficina municipal correspondiente.'],['Recoge la tarjeta','Se entrega tras la aprobación con vigencia definida.'],['Úsala correctamente','Debe estar visible en el parabrisas cuando la use el titular.']],
  links:[['Administración española','https://administracion.gob.es','information']] },
{ cat:'vehiculos', t:'Consulta y pago de multas de tráfico', s:'pago-multas-dgt',
  sd:'Consulta y paga tus multas de tráfico con descuento por pago voluntario.',
  d:'Las sanciones de tráfico pueden consultarse y pagarse en la sede electrónica de la DGT. El pago voluntario en 20 días naturales reduce la multa un 50 %. Si no se paga en plazo, puede incrementarse y derivar en embargo o procedimientos de apremio.',
  cost:'Según la infracción (-50 % en pago voluntario)', dur:'10 minutos', url:'https://sede.dgt.gob.es',
  req:['Conocer el número de expediente o los datos del vehículo.','Pagar dentro de los 20 días naturales para el descuento.','Disponer de medios de pago electrónico para el pago online.'],
  docs:[['DNI o NIE del conductor o titular',true],['Notificación de la denuncia o número de expediente',true],['Medio de pago (tarjeta o banca electrónica)',true]],
  steps:[['Consulta las multas','En la sede electrónica de la DGT con los datos del vehículo.'],['Decide entre pagar o reclamar','El descuento del 50 % solo aplica en pago voluntario.'],['Realiza el pago','Online con tarjeta o en entidades colaboradoras.'],['Guarda el justificante','Acredita el pago en plazo ante cualquier incidencia.']],
  links:[['DGT - Pago de multas','https://sede.dgt.gob.es','official']] },

// ============ IMPUESTOS (4) ============
{ cat:'impuestos', t:'Certificado de estar al corriente de obligaciones tributarias', s:'certificado-corriente-aeat',
  sd:'Obtén el certificado de la AEAT que acredita estar al corriente con Hacienda.',
  d:'El certificado de estar al corriente de pago o devuelto en período voluntario de las obligaciones tributarias lo emite la Agencia Tributaria. Es imprescindible para contratar con las administraciones públicas, licitaciones y muchas ayudas oficiales.',
  cost:'Gratuito', dur:'10 minutos (online e inmediato)', url:'https://sede.agenciatributaria.gob.es',
  req:['Estar al corriente de las obligaciones tributarias (o solicitarlo para regularizar).','Identificarse con Cl@ve, certificado digital o DNI electrónico.','Indicar el destinatario del certificado (administración o entidad concreta).'],
  docs:[['Sistema de identificación digital (Cl@ve o certificado)',true],['NIF del solicitante',true]],
  steps:[['Accede a la sede electrónica','Sección de certificados de la AEAT.'],['Identifícate','Con Cl@ve, certificado digital o DNI electrónico.'],['Solicita el certificado','Indica el ámbito (AEAT o Administración General del Estado).'],['Descárgalo o envíalo','El certificado se genera al momento con validez legal.']],
  links:[['AEAT - Sede electrónica','https://sede.agenciatributaria.gob.es','official']] },
{ cat:'impuestos', t:'Aplazamiento o fraccionamiento de deudas tributarias', s:'aplazamiento-fraccionamiento-aeat',
  sd:'Solicita aplazar o fraccionar tus deudas con la Agencia Tributaria.',
  d:'Si no puedes pagar una deuda tributaria en plazo, puedes solicitar su aplazamiento o fraccionamiento ante la AEAT. Con importes inferiores a 30.000 € no es necesario aportar garantías, aunque devenga intereses de demora (salvo situacionies específicas).',
  cost:'Intereses de demora (sin garantías si < 30.000 €)', dur:'20 minutos', url:'https://sede.agenciatributaria.gob.es',
  req:['Estar al corriente en la presentación de las autoliquidaciones.','Solicitarlo antes del fin del periodo voluntario de pago.','Aportar garantías si la deuda supera los 30.000 €.'],
  docs:[['Modelo 096 (solicitud de aplazamiento)',true],['NIF del deudor y referencia de la deuda',true],['Propuesta de fraccionamiento (número de plazos)',true],['Garantías (aval o seguro de caución) si procede',false]],
  steps:[['Identifica la deuda','Referencia, periodo y importe pendiente.'],['Presenta el modelo 096','En la sede electrónica con certificado o Cl@ve.'],['Propón el fraccionamiento','Número de plazos y periodicidad mensual.'],['Espera la concesión','Se notifica la aprobación y el calendario de pagos.']],
  links:[['AEAT - Aplazamientos','https://sede.agenciatributaria.gob.es','official']] },
{ cat:'impuestos', t:'Devolución de ingresos indebidos a Hacienda', s:'devolucion-ingresos-indebidos',
  sd:'Recupera pagos realizados de más a la AEAT con la solicitud de devolución.',
  d:'Cuando has pagado un impuesto de más, lo has ingresado por duplicado o la deuda resultó inexistente, puedes solicitar la devolución de ingresos indebidos ante la AEAT. El plazo para solicitarla es de 4 años desde el ingreso.',
  cost:'Gratuito', dur:'15 minutos', url:'https://sede.agenciatributaria.gob.es',
  req:['Acreditar el ingreso indebido (duplicado, exceso o pago sin deuda).','Solicitarlo dentro de los 4 años desde el pago.','Indicar una cuenta bancaria a nombre del solicitante.'],
  docs:[['Modelo 105 (solicitud de devolución por ingreso indebido)',true],['Justificantes de los pagos realizados',true],['NIF del solicitante y IBAN',true]],
  steps:[['Recopila los justificantes','Cartas de pago, justificantes bancarios o autoliquidaciones.'],['Presenta el modelo 105','En la sede electrónica o presencialmente.'],['Espera la verificación','La AEAT comprueba el ingreso indebido.'],['Recibe la devolución','Se abona en la cuenta indicada tras la aprobación.']],
  links:[['AEAT - Sede electrónica','https://sede.agenciatributaria.gob.es','official']] },
{ cat:'impuestos', t:'Consulta del valor catastral y certificación del Catastro', s:'valor-catastral-catastro',
  sd:'Consulta el valor catastral de tu inmueble y solicita certificaciones oficiales.',
  d:'El valor catastral es la referencia administrativa de los inmuebles que sirve para calcular el IBI y otros impuestos. Se puede consultar gratis en la Sede Electrónica del Catastro con la referencia catastral, y solicitar certificaciones oficiales del inmueble.',
  cost:'Gratuito (consulta) - certificación según tarifa', dur:'10 minutos', url:'https://sedecatastro.oacc.es',
  req:['Conocer la referencia catastral o dirección del inmueble.','Para certificaciones, identificarse digitalmente o acudir presencialmente.','Los datos pueden variar según las declaraciones presentadas.'],
  docs:[['Referencia catastral del inmueble',true],['DNI o NIE (para certificaciones)',true],['Sistema de identificación digital (para trámites online)',false]],
  steps:[['Accede a la Sede del Catastro','Entra en sedecatastro.oacc.es.'],['Busca el inmueble','Por referencia catastral, dirección o datos del titular.'],['Consulta los datos','Valor catastral, superficie, uso y año de construcción.'],['Solicita certificación si la necesitas','Con firma electrónica o en la Gerencia del Catastro.']],
  links:[['Sede Electrónica del Catastro','https://sedecatastro.oacc.es','official']] },

// ============ IMPUESTOS (1) + EDUCACION (3) ============
{ cat:'impuestos', t:'NIF para extranjeros con fines tributarios (AEAT)', s:'nif-tributario-extranjeros',
  sd:'Obtén el NIF de persona física extranjera sin NIE para obligaciones fiscales.',
  d:'Las personas extranjeras que no residan en España pero tengan obligaciones fiscales (por ejemplo, ser propietarios o heredar bienes) pueden solicitar un NIF de persona física sin NIE ante la Agencia Tributaria, necesario para presentar impuestos y firmezas.',
  cost:'Gratuito', dur:'20 minutos', url:'https://sede.agenciatributaria.gob.es',
  req:['Ser extranjero sin NIE pero con obligaciones fiscales en España.','Acreditar la identidad con pasaporte válido.','Solicitarlo presencialmente en las oficinas de la AEAT o por representante.'],
  docs:[['Pasaporte en vigor (original y copia)',true],['Modelo de solicitud de NIF (AEAT)',true],['Justificante de la obligación fiscal (propiedad, herencia)',false],['Poder de representación (si actúa un tercero)',false]],
  steps:[['Acude a una oficina de la AEAT','Con pasaporte y justificante de la obligación fiscal.'],['Cumplimenta la solicitud','Formulario de alta de NIF para no residentes.'],['Recibe tu número NIF','Se asigna en el mismo acto en la mayoría de los casos.'],['Úsalo en tus declaraciones','Necesario para modelos fiscales y certificados.']],
  links:[['AEAT - Sede electrónica','https://sede.agenciatributaria.gob.es','official']] },
{ cat:'educacion', t:'Admisión en centros de Educación Infantil y Primaria', s:'admision-centros-infantil-primaria',
  sd:'Participa en el proceso de admisión escolar: plazos, baremo y documentación.',
  d:'El proceso de admisión en centros públicos y concertados de Infantil y Primaria se realiza cada año en la comunidad autónoma de residencia. Las solicitudes se valoran con un baremo (renta, hermanos en el centro, proximidad) y se asignan plazas según la puntuación.',
  cost:'Gratuito', dur:'30 minutos (en el periodo de admisión)', url:'https://administracion.gob.es',
  req:['Estar empadronado en la comunidad autónoma.','Presentar la solicitud dentro del plazo oficial de admisión.','Indicar las preferencias de centros (varias opciones recomendadas).','Acreditar los méritos del baremo con la documentación.'],
  docs:[['Solicitud de admisión oficial de tu comunidad',true],['Libro de familia o certificado de nacimiento del alumno',true],['Certificado de empadronamiento',true],['Justificantes del baremo (renta, discapacidad, hermanos)',false]],
  steps:[['Consulta el calendario','Cada CCAA publica fechas de solicitud y adjudicación.'],['Presenta la solicitud','Online o en los centros designados.'],['Aporta los méritos','Documentación del baremo para maximizar la puntuación.'],['Comprueba la adjudicación','Acepta la plaza en el plazo indicado.']],
  links:[['Administración española - Educación','https://administracion.gob.es','information']] },
{ cat:'educacion', t:'Ayudas para libros de texto y material didáctico', s:'ayudas-material-didactico',
  sd:'Solicita las ayudas oficiales para libros de texto y material escolar.',
  d:'El Ministerio y las comunidades autónomas convocan ayudas para la adquisición de libros de texto y material didáctico para alumnado de Primaria, ESO y ciclos formativos, con criterios de renta familiar y rendimiento escolar.',
  cost:'Gratuito', dur:'20 minutos', url:'https://www.educacionfpydeportes.gob.es',
  req:['Estar matriculado en un curso elegible (Primaria, ESO o FP).','Cumplir los umbrales de renta y patrimonio familiar.','Presentar la solicitud dentro del plazo de la convocatoria.'],
  docs:[['Solicitud oficial de la convocatoria',true],['DNI o NIE del solicitante y del alumno',true],['Número de cuenta bancaria (IBAN)',true],['Justificantes de renta y composición familiar',true]],
  steps:[['Consulta la convocatoria','Revisa los umbrales de renta y los cursos elegibles.'],['Presenta la solicitud','En la plataforma oficial o presencialmente.'],['Adjunta la documentación','Rentas, composición familiar e IBAN.'],['Recibe la ayuda','Se abona o se entrega en material según la modalidad.']],
  links:[['Ministerio de Educación y FP','https://www.educacionfpydeportes.gob.es','official']] },
{ cat:'educacion', t:'Homologación de títulos extranjeros no universitarios', s:'homologacion-titulos-extranjeros',
  sd:'Homologa tu título extranjero de educación no universitaria al sistema español.',
  d:'La homologación equipara un título extranjero de educación no universitaria (bachillerato, FP) al título español correspondiente. La tramita el Ministerio de Educación y permite acceder a estudios, empleos y oposiciones con el título homologado.',
  cost:'Gratuito', dur:'30 minutos (resolución en meses)', url:'https://sede.educacion.gob.es',
  req:['Tener un título extranjero oficial de educación no universitaria.','Presentar la solicitud en modelo oficial.','Aportar el título legalizado y traducido (si procede).'],
  docs:[['Modelo oficial de solicitud de homologación',true],['Título extranjero oficial (legalizado o apostillado)',true],['Certificación académica de los estudios cursados',true],['Traducción oficial si el documento no está en español',true]],
  steps:[['Legaliza y traduce el título','Apostilla de La Haya y traducción oficial si procede.'],['Presenta la solicitud','En la sede electrónica del Ministerio o registro oficial.'],['Abona la tasa si procede','Algunas modalidades tienen tasas establecidas.'],['Espera la resolución','La homologación permite ejercer derechos académicos y profesionales.']],
  links:[['Sede electrónica de Educación','https://sede.educacion.gob.es','official']] },

// ============ EDUCACION (2) + EXTRANJERIA (2) ============
{ cat:'educacion', t:'Pruebas libres para la obtención del Graduado en ESO', s:'pruebas-libres-eso',
  sd:'Obtén el título de Graduado en ESO mediante pruebas libres para adultos.',
  d:'Las personas mayores de 18 años (o 16 en casos excepcionales) que no obtuvieron el Graduado en ESO pueden presentarse a pruebas libres convocadas por las comunidades autónomas. Superarlas permite obtener el título oficial y continuar estudios de Bachillerato o FP.',
  cost:'Gratuito', dur:'20 minutos (inscripción)', url:'https://administracion.gob.es',
  req:['Ser mayor de 18 años (o 16 con justificación laboral o formativa).','Inscribirse en el plazo de convocatoria de tu comunidad autónoma.','Superar las pruebas de los ámbitos convocados.'],
  docs:[['DNI o NIE en vigor',true],['Solicitud de inscripción en la prueba',true],['Certificados académicos previos (si se tienen)',false]],
  steps:[['Consulta la convocatoria','Tu comunidad autónoma publica fechas y ámbitos evaluados.'],['Inscríbete en el plazo','Online o en las oficinas designadas.'],['Prepara los ámbitos','Científico-tecnológico, social, comunicación y aprendizaje.'],['Obtén el título','Superar las pruebas da derecho al Graduado en ESO oficial.']],
  links:[['Administración española - Educación','https://administracion.gob.es','information']] },
{ cat:'educacion', t:'Solicitud del título oficial de Bachiller', s:'titulo-bachiller',
  sd:'Tramita el título oficial de Bachiller tras superar la etapa en tu comunidad.',
  d:'El título de Bachiller se obtiene al superar la etapa (2 cursos) y lo expide la comunidad autónoma donde se cursaron los estudios. Es requisito para acceder a la universidad (junto a la EBAU) y a los ciclos formativos de grado superior.',
  cost:'Gratuito', dur:'20 minutos', url:'https://www.educacionfpydeportes.gob.es',
  req:['Haber superado los dos cursos de Bachiller.','Solicitarlo en el centro educativo u organismo autonómico.','Presentar la solicitud en el plazo que fije tu comunidad.'],
  docs:[['DNI o NIE del interesado (o del representante si es menor)',true],['Expediente académico de Bachiller',true],['Solicitud oficial del organismo autonómico',true]],
  steps:[['Comprueba que tienes la etapa superada','El centro verifica el expediente académico.'],['Solicita el título','En el propio centro u oficina de educación.'],['Espera la expedición','El organismo autonómico emite el título oficial.'],['Recoge el documento','Necesario para EBAU, FP de grado superior y empleo.']],
  links:[['Ministerio de Educación y FP','https://www.educacionfpydeportes.gob.es','information']] },
{ cat:'extranjeria', t:'Primera expedición de la Tarjeta de Identidad de Extranjero (TIE)', s:'primera-expedicion-tie',
  sd:'Obtén tu TIE tras conseguir tu autorización de residencia: cita, tasa y huellas.',
  d:'La Tarjeta de Identidad de Extranjero (TIE) acredita la situación legal y la identidad de los extranjeros con autorización de residencia superior a 6 meses. Debe solicitarse en el plazo de un mes desde la entrada o la concesión de la autorización.',
  cost:'19,45 € (tasa modelo 790 código 012)', dur:'45 minutos (con cita previa)', url:'https://icp.administracionelectronica.gob.es',
  req:['Tener una autorización de residencia o residencia y trabajo superior a 6 meses.','Solicitar cita previa para expedición (o «toma de huellas»).','Abonar la tasa 790-012 y aportar el justificante.','Acudir personalmente con la documentación completa.'],
  docs:[['Pasaporte completo en vigor',true],['Resolución de concesión de la autorización',true],['Justificante del pago de la tasa 790-012',true],['Fotografía reciente a color (fondo blanco)',true],['Padrón municipal (para renovaciones)',false]],
  steps:[['Obtén la autorización favorable','Resolución positiva del expediente de residencia.'],['Paga la tasa 790-012','Y reserva cita para la toma de huellas.'],['Acude a la cita','Presenta documentación completa y registra huellas.'],['Recoge la tarjeta','En unos 30-40 días, con cita de recogida.']],
  links:[['Cita previa extranjeros','https://icp.administracionelectronica.gob.es','appointment'],['Sede de extranjería','https://sede.administracionespublicas.gob.es','official']] },
{ cat:'extranjeria', t:'Renovación de la autorización de residencia temporal', s:'renovacion-residencia-temporal',
  sd:'Renueva tu residencia temporal 60 días antes de su caducidad: requisitos y plazos.',
  d:'Las autorizaciones de residencia temporal se renuevan durante los 60 días previos a la caducidad (o dentro de los 90 días posteriores, con posible sanción). La renovación exige acreditar los requisitos iniciales, como medios económicos y cotizaciones si procede.',
  cost:'Tasa modelo 790 código 052 (según modalidad)', dur:'30 minutos', url:'https://sede.administracionespublicas.gob.es',
  req:['Presentar la solicitud en los 60 días previos a la caducidad (o 90 posteriores).','Acreditar medios económicos suficientes y seguro (si aplica).','Acreditar actividad laboral o cotizaciones si la residencia es por trabajo.','Mantener el empadronamiento vigente.'],
  docs:[['Modelo oficial de solicitud (EX-00 o similar)',true],['Pasaporte completo en vigor',true],['Justificante de la tasa abonada',true],['Justificantes de medios económicos y cotización',true],['Certificado de empadronamiento',false]],
  steps:[['Prepara la documentación','Requisitos económicos, laborales y de empadronamiento.'],['Presenta la renovación','En la sede electrónica o oficina de extranjería.'],['Abona la tasa','Modelo 790-052 correspondiente.'],['Espera la resolución','Tras la aprobación, renueva también la TIE si caduca.']],
  links:[['Sede de extranjería','https://sede.administracionespublicas.gob.es','official']] },

// ============ EXTRANJERIA (2) ============
{ cat:'extranjeria', t:'Autorización de residencia por arraigo social', s:'arraigo-social',
  sd:'Solicita el arraigo social: residencia temporal para inmigrantes consolidados.',
  d:'El arraigo social permite obtener una autorización de residencia temporal a extranjeros que llevan al menos 2 años en España (sin ser residentes legales), acreditan medios económicos y cuentan con un contrato de trabajo o informes favorables de arraigo.',
  cost:'Tasa modelo 790 código 052', dur:'30 minutos', url:'https://sede.administracionespublicas.gob.es',
  req:['Permanencia continuada en España durante al menos 2 años.','Falta de antecedentes penales en España y país de origen.','Contrato de trabajo de al menos 30 horas semanales (o informe de arraigo).','Acreditar medios económicos suficientes.'],
  docs:[['Modelo oficial EX-10 con la solicitud',true],['Pasaporte completo en vigor',true],['Certificado de empadronamiento que acredite los 2 años',true],['Certificado de antecedentes penales',true],['Contrato de trabajo o informe municipal de arraigo',true]],
  steps:[['Reúne la documentación','Empadronamiento, antecedentes, contrato o informe de arraigo.'],['Presenta la solicitud','En la sede electrónica u oficina de extranjería.'],['Abona la tasa','Modelo 790-052.'],['Resolución y TIE','Si es favorable, tramita la TIE para acreditarte.']],
  links:[['Sede de extranjería','https://sede.administracionespublicas.gob.es','official']] },
{ cat:'extranjeria', t:'Autorización de trabajo por cuenta ajena (régimen general)', s:'autorizacion-trabajo-cuenta-ajena',
  sd:'Tramita la autorización inicial de trabajo por cuenta ajena para extranjeros.',
  d:'Los extranjeros no residentes legalmente en España necesitan una autorización de trabajo por cuenta ajena para ser contratados. La solicita el empleador ante la oficina de extranjería, justificando la situación nacional de empleo y el contrato de trabajo.',
  cost:'Tasa modelo 790 (código 052/053 según régimen)', dur:'30 minutos', url:'https://sede.administracionespublicas.gob.es',
  req:['Que el empleador presente la solicitud con contrato firmado.','Situación nacional de empleo favorable o ocupación en escasez.','Falta de antecedentes penales del trabajador.','Acreditación de la identidad y pasaporte vigente.'],
  docs:[['Solicitud oficial del empleador',true],['Contrato de trabajo firmado por ambas partes',true],['Copia completa del pasaporte del trabajador',true],['Antecedentes penales del país de origen',true],['Titulación o colegiación si la profesión la exige',false]],
  steps:[['El empleador presenta la solicitud','Con contrato y documentación del puesto.'],['Tramitación y resolución','La Oficina de Extranjería resuelve en el plazo legal.'],['Visado (si procede)','El trabajador solicita el visado en el consulado español.'],['Alta en Seguridad Social y TIE','Al llegar a España, se formaliza el alta y la tarjeta.']],
  links:[['Sede de extranjería','https://sede.administracionespublicas.gob.es','official']] },

// ============ EXTRANJERIA (2) ============
{ cat:'extranjeria', t:'Nacionalidad española por residencia', s:'nacionalidad-espanola-residencia',
  sd:'Solicita la nacionalidad española tras 10 años de residencia legal y continua.',
  d:'La nacionalidad española por residencia requiere 10 años de residencia legal, continuada e inmediatamente anterior a la solicitud (5 para refugiados, 2 para iberoamericanos y otros supuestos, 1 para casados con español). Se tramita ante el Ministerio de Justicia.',
  cost:'Tasa modelo 107', dur:'30 minutos (pruebas DELE/CCSE aparte)', url:'https://sede.mjusticia.gob.es',
  req:['Residencia legal, continuada e inmediatamente anterior (10 años general).','Buena conducta cívica y suficiente grado de integración.','Superar las pruebas DELE y CCSE (si no hay exención).','Renunciar a la nacionalidad anterior (salvo países exceptuados).'],
  docs:[['Solicitud oficial (modelo normalizado)',true],['Pasaporte y NIE en vigor',true],['Certificado de empadronamiento',true],['Certificado de antecedentes penales del país de origen',true],['Certificados DELE y CCSE aprobados',true]],
  steps:[['Comprueba tu plazo de residencia','10 años general; reducido para supuestos especiales.'],['Acredita integración','Pruebas CCSE (constitución) y DELE (idioma) si no estás exento.'],['Presenta la solicitud','Online en la sede del Ministerio de Justicia.'],['Seguimiento y juramento','Tras la concesión, se realiza el juramento o promesa.']],
  links:[['Ministerio de Justicia - Nacionalidad','https://sede.mjusticia.gob.es','official']] },
{ cat:'extranjeria', t:'Visado de estancia por estudios (visado de estudios)', s:'visado-estudios',
  sd:'Solicita el visado de estudios para cursar programas en España (más de 90 días).',
  d:'El visado de estancia por estudios habilita a extranjeros no comunitarios a permanecer en España para realizar estudios, formación, investigación o intercambio por más de 90 días. Se solicita en el consulado español del país de residencia del interesado.',
  cost:'Tasa consular según nacionalidad (aprox. 80 €)', dur:'1 hora (resolución en semanas)', url:'https://www.exteriores.gob.es',
  req:['Estar admitido en un centro de estudios autorizado en España.','Acreditar medios económicos y alojamiento para la estancia.','Disponer de seguro médico completo en España.','Falta de antecedentes penales (para estancias largas).'],
  docs:[['Pasaporte válido (mínimo vigencia de la estancia)',true],['Carta de admisión del centro de estudios',true],['Acreditación de medios económicos y alojamiento',true],['Seguro médico de cobertura completa',true],['Certificado de antecedentes penales (si procede)',false]],
  steps:[['Solicita la admisión del centro','Debe estar autorizado para acoger estudiantes extranjeros.'],['Pide cita en el consulado','Y presenta la solicitud con la documentación completa.'],['Espera la resolución','El visado se resuelve en el plazo consular indicado.'],['Recoge el visado y viaja','Tras llegar, tramita la TIE si la estancia supera 6 meses.']],
  links:[['Ministerio de Asuntos Exteriores','https://www.exteriores.gob.es','official']] },

// ============ VIVIENDA (4) ============
{ cat:'vivienda', t:'Certificado de eficiencia energética de vivienda', s:'certificado-eficiencia-energetica',
  sd:'Obtén el certificado de eficiencia energética obligatorio para vender o alquilar.',
  d:'El certificado de eficiencia energética (CEE) valora el consumo de energía de una vivienda y es obligatorio para venderla o alquilarla. Lo emiten técnicos cualificados y se registra en el organismo autonómico correspondiente.',
  cost:'Aprox. 100-300 € (según vivienda y técnico)', dur:'1-2 horas de visita técnica', url:'https://administracion.gob.es',
  req:['Contratar a un técnico cualificado (arquitecto, ingeniero).','Realizar la visita técnica y obtener el certificado.','Registrar el certificado en el organismo autonómico.','Incluir la etiqueta energética en los anuncios de venta o alquiler.'],
  docs:[['Planos o descripción de la vivienda',true],['Datos de instalaciones (clima, agua caliente)',true],['DNI o NIE del propietario',true]],
  steps:[['Contrata un técnico cualificado','Realizará la visita y calculará la calificación.'],['Visita técnica','Recopila datos de envolvente e instalaciones.'],['Obtén el certificado y la etiqueta','Con la calificación de A a G.'],['Regístralo en tu comunidad','Necesario para publicitar la vivienda legalmente.']],
  links:[['Administración española','https://administracion.gob.es','information']] },
{ cat:'vivienda', t:'Cédula de habitabilidad', s:'cedula-habitabilidad',
  sd:'Tramita la cédula de habitabilidad, documento obligatorio en varias comunidades.',
  d:'La cédula de habitabilidad acredita que una vivienda cumple las condiciones mínimas de habitabilidad (superficie, instalaciones, salubridad). Es obligatoria para ocupar la vivienda y para contratar suministros en comunidades como Cataluña o Baleares.',
  cost:'Tasa autonómica (aprox. 15-100 €)', dur:'30 minutos (resolución en semanas)', url:'https://administracion.gob.es',
  req:['Que la vivienda cumpla los requisitos de habitabilidad de la CCAA.','Contratar a un técnico para el certificado de habitabilidad.','Presentar la solicitud ante el organismo autonómico.'],
  docs:[['Certificado técnico de habitabilidad',true],['DNI o NIE del propietario',true],['Justificante del pago de la tasa',true],['Escritura o referencia catastral de la vivienda',false]],
  steps:[['Contrata un técnico','Emite el certificado tras inspeccionar la vivienda.'],['Presenta la solicitud','En el organismo autonómico de vivienda.'],['Abona la tasa','Según la tarifa de tu comunidad autónoma.'],['Recibe la cédula','Con vigencia definida (10-15 años según CCAA).']],
  links:[['Administración española','https://administracion.gob.es','information']] },
{ cat:'vivienda', t:'Inscripción en programas de Vivienda de Protección Oficial (VPO)', s:'inscripcion-vpo',
  sd:'Inscríbete en el registro de solicitantes de vivienda de protección oficial.',
  d:'Para optar a una vivienda de protección oficial (VPO) en venta, alquiler o cesión, hay que inscribirse en el registro de demandantes de vivienda protegida de la comunidad autónoma o municipio. Los ingresos familiares y la situación determinan la elegibilidad.',
  cost:'Gratuito', dur:'30 minutos', url:'https://administracion.gob.es',
  req:['Cumplir los límites de renta familiar establecidos.','No ser titular de otra vivienda en propiedad (regla general).','Estar empadronado en la zona del programa.','Renovar la inscripción periódicamente para no perder puestos.'],
  docs:[['Solicitud de inscripción oficial',true],['DNI o NIE de los miembros de la unidad familiar',true],['Justificantes de ingresos y renta (IRPF, nóminas)',true],['Certificado de empadronamiento',true]],
  steps:[['Comprueba los requisitos','Renta familiar, empadronamiento y ausencia de otra vivienda.'],['Inscríbete en el registro','Autonómico o municipal según el programa.'],['Mantén la inscripción','Renuévala en los plazos fijados.'],['Participa en los sorteos o adjudicaciones','Según los regímenes de cada promoción.']],
  links:[['Administración española','https://administracion.gob.es','information']] },
{ cat:'vivienda', t:'Aplazamiento de hipoteca por dificultades (Código de Buenas Prácticas)', s:'aplazamiento-hipoteca-cbp',
  sd:'Solicita la carencia o reestructuración de tu hipoteca si estás en riesgo.',
  d:'Los deudores hipotecarios en dificultades pueden acogerse a los Códigos de Buenas Prácticas y medidas extraordinarias: carencia de capital, reducción temporal del tipo o quita en el caso de resolución. Se solicita directamente en el banco, con protocolo de reclamación al servicio de atención al cliente y al Banco de España si se deniega.',
  cost:'Gratuito (sujeto a condiciones del código aplicable)', dur:'30 minutos', url:'https://www.bde.es',
  req:['Estar en riesgo de vulnerabilidad económica según los umbrales del código.','Que el préstamo sea sobre vivienda habitual.','Que la entidad haya adherido al código aplicable o esté obligada por ley.','Solicitarlo antes de la subasta si ya hay procedimiento.'],
  docs:[['Solicitud formal a la entidad',true],['Justificantes de la situación económica (paro, ERTE, ingresos)',true],['Certificado de empadronamiento y composición familiar',true],['Declaración responsable de patrimonio',true]],
  steps:[['Presenta la solicitud en tu banco','Con la documentación de vulnerabilidad económica.'],['Negocia la reestructuración','Carencia, reducción de tipo o ampliación de plazo.'],['Si se deniega, reclama','Al servicio de atención al cliente y al Banco de España.'],['Comprueba las medidas extraordinarias','Aplicables según la normativa vigente.']],
  links:[['Banco de España','https://www.bde.es','information']] },

// ============ VIVIENDA (2) + EMPRESAS (2) ============
{ cat:'vivienda', t:'Licencia de primera ocupación de vivienda', s:'licencia-primera-ocupacion',
  sd:'Tramita la licencia de primera ocupación para estrenar vivienda legalmente.',
  d:'La licencia de primera ocupación (o cédula, según la comunidad) acredita que una vivienda de nueva construcción cumple los requisitos para ser habitada. Es imprescindible para contratar suministros, empadronarse y, en muchos casos, para la compraventa.',
  cost:'Tasa municipal o autonómica (aprox. 50-200 €)', dur:'30 minutos (resolución en semanas)', url:'https://administracion.gob.es',
  req:['Que la vivienda esté terminada conforme a la licencia de obras.','Presentar el certificado técnico final de obra.','Solicitarla ante el ayuntamiento o la comunidad autónoma.'],
  docs:[['Certificado técnico final de obra del arquitecto',true],['Dirección o licencia de obra del edificio',true],['DNI o NIE del solicitante',true],['Justificante del pago de la tasa',true]],
  steps:[['Obtén el certificado final de obra','Emitido por el técnico director de la obra.'],['Solicita la licencia','En la oficina municipal o autonómica de vivienda.'],['Abona la tasa','Según la tarifa local.'],['Recibe la licencia','Permite empadronamiento y contratación de suministros.']],
  links:[['Administración española','https://administracion.gob.es','information']] },
{ cat:'vivienda', t:'Nota simple registral de una vivienda', s:'nota-simple-registral',
  sd:'Solicita la nota simple del Registro de la Propiedad: titularidad y cargas.',
  d:'La nota simple es un documento informativo del Registro de la Propiedad que refleja la titularidad, descripción y cargas (hipotecas, embargos) de un inmueble. Es imprescindible antes de comprar una vivienda para conocer su situación jurídica real.',
  cost:'Aprox. 9-15 € (online)', dur:'10 minutos (entrega en 24-48 h)', url:'https://www.registradores.org',
  req:['Conocer la identificación registral del inmueble (finca o dirección).','Solicitarla en el Colegio de Registradores o registro competente.','Justificar interés legítimo en algunos supuestos.'],
  docs:[['Identificación del inmueble (referencia registral o catastral)',true],['DNI o NIE del solicitante',true],['Medio de pago de la tarifa',true]],
  steps:[['Accede al portal de Registradores','O al registro de la propiedad correspondiente.'],['Localiza la finca','Por referencia registral, catastral o dirección.'],['Solicita y paga la nota','Tarifa oficial según modalidad.'],['Recibe el documento','Digital en 24-48 horas con cargas y titularidad.']],
  links:[['Colegio de Registradores','https://www.registradores.org','official']] },
{ cat:'empresas', t:'Certificado de disponibilidad de denominación social', s:'certificado-denominacion-social',
  sd:'Reserva el nombre de tu empresa en el Registro Mercantil antes de constituirla.',
  d:'La certificación negativa de denominación social acredita que el nombre elegido para tu empresa no está registrado. Es el primer paso para constituir una sociedad (SL, SA) y tiene una vigencia de 3 meses desde su expedición.',
  cost:'Aprox. 15 €', dur:'15 minutos (resolución en 24-72 h)', url:'https://www.registradores.org',
  req:['Proponer 3 denominaciones por orden de preferencia.','Solicitarla en el Registro Mercantil Central.','Estar vigente al constituir la sociedad (3 meses).'],
  docs:[['Solicitud con las 3 denominaciones propuestas',true],['DNI o NIE del solicitante',true],['Justificante del pago de la tarifa',true]],
  steps:[['Elige 3 nombres alternativos','Por orden de preferencia para agilizar la concesión.'],['Solicita la certificación','Online en el Registro Mercantil Central.'],['Espera la resolución','El RMC verifica que no exista denominación igual.'],['Úsala en la escritura','La denominación reservada se usa en la constitución.']],
  links:[['Registro Mercantil Central','https://www.registradores.org','official']] },
{ cat:'empresas', t:'Constitución de una Sociedad Limitada (SL)', s:'constitucion-sociedad-limitada',
  sd:'Crea tu Sociedad Limitada: escritura notarial, inscripción y tasas.',
  d:'La Sociedad Limitada es la forma jurídica más habitual para empresas en España. Su constitución exige el certificado de denominación, la escritura notarial con los estatutos y socios, el depósito del capital social (desde 1 €) y la inscripción en el Registro Mercantil.',
  cost:'Tasas notariales y registrales (aprox. 300-600 €)', dur:'1-2 semanas', url:'https://www.registradores.org',
  req:['Obtener el certificado de denominación social vigente.','Otorgar escritura pública de constitución ante notario.','Depositar el capital social (mínimo legal 1 €).','Inscribir la sociedad en el Registro Mercantil.'],
  docs:[['Certificado de denominación social del RMC',true],['DNI o NIE de todos los socios fundadores',true],['Proyecto de estatutos sociales',true],['Justificante del depósito del capital social',true]],
  steps:[['Reserva el nombre','Con el certificado negativo de denominación.'],['Otorga la escritura','Ante notario, con estatutos y socios.'],['Inscribe en el Registro Mercantil','Presentando la escritura y liquidando tasas.'],['Da de alta la sociedad','AEAT (036) y Seguridad Social para contratar.']],
  links:[['Registro Mercantil','https://www.registradores.org','official']] },

// ============ EMPRESAS (3) + CONSUMO (1) ============
{ cat:'empresas', t:'Inscripción de la empresa en la Seguridad Social (cuenta de cotización)', s:'cuenta-cotizacion-empresa',
  sd:'Abre la cuenta de cotización de tu empresa para contratar trabajadores.',
  d:'Toda empresa que vaya a contratar trabajadores debe inscribirse en la Seguridad Social, obteniendo un Código de Cuenta de Cotización (CCC). Es el paso previo obligatorio al alta de los empleados y se tramita en la Tesorería General de la Seguridad Social (TGSS).',
  cost:'Gratuito', dur:'20 minutos', url:'https://sede.seg-social.gob.es',
  req:['Tener el alta censal en Hacienda (modelo 036/037) previa.','Inscribir la empresa antes del inicio de la actividad con trabajadores.','Indicar la actividad económica (CNAE) correcta.'],
  docs:[['Solicitud de inscripción (modelo TA.6)',true],['Alta censal (modelo 036/037)',true],['DNI o NIE del empresario o representante',true],['Titularidad del local o contrato de alquiler',false]],
  steps:[['Realiza el alta censal','Modelo 036/037 en la AEAT si aún no la tienes.'],['Presenta el modelo TA.6','En la TGSS, presencial u online con certificado digital.'],['Recibe el Código de Cuenta de Cotización','Necesario para las altas de trabajadores.'],['Da de alta a tus trabajadores','Antes del inicio de su actividad laboral.']],
  links:[['Seguridad Social - Sede electrónica','https://sede.seg-social.gob.es','official']] },
{ cat:'empresas', t:'Comunicación de contratos de trabajo (Sistema Contrat@)', s:'comunicacion-contratos-contrat',
  sd:'Registra los contratos de tus trabajadores en el sistema Contrat@ del SEPE.',
  d:'Las empresas deben comunicar al Servicio Público de Empleo Estatal (SEPE) el contenido de los contratos de trabajo que formalicen, mediante el sistema Contrat@, en los 10 días siguientes a su firma. Es obligatorio y gratuito.',
  cost:'Gratuito', dur:'15 minutos', url:'https://sede.sepe.gob.es',
  req:['Tener identificación digital (certificado, Cl@ve o usuario Contrat@).','Comunicar cada contrato en los 10 días siguientes a su firma.','Incluir modalidad, duración y datos del puesto.'],
  docs:[['Contrato de trabajo firmado',true],['DNI o NIE del trabajador',true],['Certificado digital o usuario del sistema Contrat@',true]],
  steps:[['Accede al sistema Contrat@','En la sede del SEPE con tu identificación digital.'],['Registra el contrato','Modalidad, duración, puesto y datos del trabajador.'],['Obtén el número de carpeta','Justificante de la comunicación realizada.'],['Archivo obligatorio','Conserva el contrato y la comunicación en tu empresa.']],
  links:[['SEPE - Contrat@','https://sede.sepe.gob.es','official']] },
{ cat:'empresas', t:'Inscripción de la sociedad en el Registro Mercantil', s:'registro-mercantil-sociedad',
  sd:'Inscribe tu sociedad en el Registro Mercantil para adquirir plena personalidad.',
  d:'La inscripción en el Registro Mercantil otorga a la sociedad su plena eficacia jurídica frente a terceros. Se presenta la escritura de constitución (o actos posteriores: ampliaciones, cambios de órgano, disolución) en el Registro Mercantil Provincial correspondiente.',
  cost:'Tasa registral (según capital, aprox. 150-400 €)', dur:'20 minutos (resolución en 15 días)', url:'https://www.registradores.org',
  req:['Contar con la escritura pública notarial de los actos.','Presentar la inscripción en el plazo de 2 meses desde el otorgamiento.','Liquidar la tasa registral correspondiente.'],
  docs:[['Escritura pública notarial',true],['Modelo oficial de presentación registral',true],['Justificante del pago de la tasa',true],['NIF provisional o definitivo de la sociedad',true]],
  steps:[['Obtén el NIF de la sociedad','Provisional en la AEAT tras la escritura.'],['Presenta la escritura en el Registro','Con el modelo de presentación y la tasa.'],['Espera la calificación registral','El registrador inscribe o suspende con defectos subsanables.'],['Publica la inscripción','La sociedad queda plenamente operativa frente a terceros.']],
  links:[['Registro Mercantil','https://www.registradores.org','official']] },
{ cat:'consumo', t:'Reclamación en materia de consumo', s:'reclamacion-consumo',
  sd:'Reclama ante las autoridades de consumo por productos o servicios defectuosos.',
  d:'Cuando una empresa no responde a tus quejas sobre un producto o servicio (compras, telecomunicaciones, energía, reparaciones), puedes presentar una reclamación en las oficinas municipales o autonómicas de consumo, preferiblemente con la hoja de reclamaciones oficial.',
  cost:'Gratuito', dur:'20 minutos', url:'https://consumo.gob.es',
  req:['Haber reclamado primero a la empresa (guarda el justificante).','Disponer de hoja de reclamaciones o justificantes de compra.','Identificar el establecimiento y el hecho reclamado.'],
  docs:[['Hoja de reclamaciones (copia rosa o justificante)',true],['Factura o ticket de compra',true],['DNI o NIE del reclamante',true],['Copia de la reclamación previa a la empresa',false]],
  steps:[['Reclama a la empresa','Por escrito, guardando copia sellada o certificado.'],['Presenta la reclamación oficial','En consumo municipal o autonómico, u online.'],['Aporta la documentación','Ticket, hoja de reclamaciones y comunicación previa.'],['Espera la mediación','Los servicios de consumo pueden mediar o inspeccionar.']],
  links:[['Agencia Española de Consumo','https://consumo.gob.es','official']] },

// ============ CONSUMO (4) ============
{ cat:'consumo', t:'Reclamación ante la Agencia Española de Protección de Datos (AEPD)', s:'reclamacion-aepd',
  sd:'Denuncia a la AEPD usos indebidos de tus datos personales o spam persistente.',
  d:'Si una empresa usa tus datos personales sin consentimiento, no atiende tu solicitud de baja, o te envía publicidad tras oponerte, puedes reclamar a la AEPD. Primero debe reclamarse a la empresa responsable y, si no responde en un mes, presentar la reclamación.',
  cost:'Gratuito', dur:'20 minutos', url:'https://sedeagpd.gob.es',
  req:['Haber reclamado previamente a la empresa responsable.','Esperar el plazo de un mes para la respuesta.','Acreditar los hechos con capturas, correos o comunicaciones.','Presentar la reclamación dentro de los 6 meses siguientes.'],
  docs:[['Formulario de reclamación de la AEPD',true],['DNI o NIE del reclamante',true],['Justificante de la reclamación previa a la empresa',true],['Pruebas de la infracción (capturas, emails, SMS)',true]],
  steps:[['Reclama a la empresa','Ejerce tus derechos ARSOPL: acceso, rectificación, supresión, oposición, limitación y portabilidad.'],['Reúne las pruebas','Comunicaciones enviadas y respuestas recibidas.'],['Presenta la reclamación','En la sede electrónica de la AEPD con firma digital.'],['Sigue las instrucciones','La AEPD puede requerir información y sancionar la infracción.']],
  links:[['AEPD - Sede electrónica','https://sedeagpd.gob.es','official']] },
{ cat:'consumo', t:'Reclamación por cancelación, retraso o pérdida de equipaje (AESA)', s:'reclamacion-vuelos-aesa',
  sd:'Reclama tus derechos como pasajero aéreo ante AESA: compensaciones y asistencia.',
  d:'Ante cancelaciones, grandes retrasos (más de 3 horas a la llegada), denegación de embarque o pérdida de equipaje, los pasajeros tienen derechos en la UE (Reglamento 261/2004). Si la aerolínea no responde o deniega la compensación, puedes reclamar a la Agencia Estatal de Seguridad Aérea (AESA).',
  cost:'Gratuito', dur:'20 minutos', url:'https://www.seguridadaerea.gob.es',
  req:['Vuelo dentro de la UE o con aerolínea europea (o salida de la UE).','Haber reclamado primero a la aerolínea (y esperar 2 meses para denegación).','Acreditar la reserva, la incidencia y los gastos ocasionados.','Solicitarlo generalmente dentro de los 5 años (según CCAA).'],
  docs:[['Reserva y tarjeta de embarque',true],['DNI o NIE del pasajero',true],['Justificante de la reclamación previa a la aerolínea',true],['Justificantes de gastos (comida, hotel, transporte)',false]],
  steps:[['Reclama a la aerolínea','Por sus canales oficiales, guardando el justificante.'],['Espera la respuesta','2 meses (cancelación/retraso) o 6 semanas (equipaje).'],['Presenta tu caso en la plataforma AESA','La «plataforma de resolución alternativa de litigios».'],['Recibe la resolución','AESA facilita un dictamen para resolver el conflicto.']],
  links:[['AESA - Derechos de los pasajeros','https://www.seguridadaerea.gob.es','official']] },
{ cat:'consumo', t:'Inscripción en la Lista Robinson', s:'lista-robinson',
  sd:'Date de alta en la Lista Robinson para no recibir publicidad no deseada.',
  d:'La Lista Robinson es el sistema de exclusión publicitaria gestionado por la Federación de Comercio Electrónico y Marketing Directo. Al inscribirte, las empresas adheridas dejan de enviarte publicidad postal, telefónica o por email si no tienen tu consentimiento expreso.',
  cost:'Gratuito', dur:'10 minutos', url:'https://www.listarobinson.es',
  req:['Ser mayor de 14 años.','Registrar tus datos personales (nombre, DNI, dirección, teléfono).','Renovar el alta cada 3 años para mantenerla activa.'],
  docs:[['DNI o NIE del solicitante',true],['Datos de contacto a inscribir',true],['Email para confirmar el alta',true]],
  steps:[['Accede a listarobinson.es','Crea tu cuenta con tus datos personales.'],['Confirma el alta','Mediante el email de verificación.'],['Espera la difusión','Las empresas actualizan sus ficheros periódicamente.'],['Renueva cada 3 años','Para mantener la exclusión publicitaria activa.']],
  links:[['Lista Robinson','https://www.listarobinson.es','official']] },
{ cat:'consumo', t:'Reclamación ante el Banco de España por servicios financieros', s:'reclamacion-banco-espana',
  sd:'Reclama al Banco de España contra tu banco por comisiones o malas prácticas.',
  d:'Si tu banco rechaza o ignora tu reclamación sobre comisiones, hipoteca, tarjetas u otros servicios, puedes acudir al Departamento de Conducta de Entidades del Banco de España. Es necesario haber reclamado primero al Servicio de Atención al Cliente del banco.',
  cost:'Gratuito', dur:'20 minutos', url:'https://reclamaciones.bde.es',
  req:['Haber reclamado primero al servicio de atención al cliente (o defensor del cliente).','Esperar 15 días hábiles (2 meses para el defensor del cliente).','Presentar la reclamación dentro del plazo de un año.'],
  docs:[['Formulario de reclamación del Banco de España',true],['DNI o NIE del reclamante',true],['Reclamación previa y respuesta del banco',true],['Contratos y documentación de la operación',true]],
  steps:[['Reclama a tu banco','Al Servicio de Atención al Cliente con número de expediente.'],['Espera la respuesta','15 días hábiles (2 meses si es el defensor del cliente).'],['Reclama al Banco de España','Online en reclamaciones.bde.es con la documentación.'],['Recibe el informe','El BdE emite un dictamen sobre las prácticas de la entidad.']],
  links:[['Banco de España - Reclamaciones','https://reclamaciones.bde.es','official']] },

// ============ CONSUMO (1) ============
{ cat:'consumo', t:'Solicitud de arbitraje de consumo', s:'arbitraje-consumo',
  sd:'Resuelve conflictos de consumo de forma rápida y gratuita mediante arbitraje.',
  d:'El arbitraje de consumo es un sistema gratuito y ágil para resolver conflictos con empresas adheridas a las juntas arbitrales de consumo, sin necesidad de ir a los tribunales. El laudo arbitral es vinculante para ambas partes.',
  cost:'Gratuito', dur:'20 minutos', url:'https://consumo.gob.es',
  req:['Que la empresa reclamada esté adherida al sistema arbitral (o lo acepte).','Haber intentado resolver el conflicto directamente con la empresa.','Presentar la solicitud en la junta arbitral de tu comunidad autónoma.'],
  docs:[['Hoja de solicitud de arbitraje (cola de la hoja de reclamaciones)',true],['Factura o justificante de compra',true],['DNI o NIE del solicitante',true],['Comunicaciones previas con la empresa',false]],
  steps:[['Comprueba la adhesión','Verifica si la empresa pertenece al sistema arbitral.'],['Presenta la solicitud','En la junta arbitral de consumo de tu comunidad.'],['Fase de arbitraje','Un colegio arbitral estudia el caso y puede convocar audiencia.'],['Laudo vinculante','La decisión es obligatoria para ambas partes.']],
  links:[['Agencia Española de Consumo','https://consumo.gob.es','official']] },
];
